baseURL = "https://mdaffin.github.io/blog/"
languageCode = "en-us"
title = "CPP GameDev"
theme = "m10c"

[params]
author = "karnage"
description = "Discussion around the gamedev"
avatar = "cppgamedev.jpg"

[[params.social]]
  name = "github"
  url = "https://github.com/cpp-gamedev"

[[params.social]]
  name = "discord"
  url = "https://discord.gg/2NvA5jn"
